title: 3veryday
description: Of our lives. We have to hold on tight, 
url: "https://3veryday.github.io"
baseurl: "" # 루트 도메인일 때
author:
  name: "3veryday"
  bio: "3veryday 개발."
  avatar: "/assets/images/profile_haru.png"
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache


header:
  navigation:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Projects"
      url: "/projects/"
    - title: "Resume"
      url: "/resume/"
